import { Noto_Sans_Javanese } from 'next/font/google';

import type { Metadata } from 'next';
import '@/styles/global.scss';

const fontStyles = Noto_Sans_Javanese({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body className={fontStyles.className}>{children}</body>
    </html>
  );
}
